// Rich category data for the Mega Menu
// Extends the existing NAVIGATION constant with featured products and editorial content
import type { NavCategory } from './navbar.types';

export const NAV_CATEGORIES: NavCategory[] = [
    {
        id: 'oturma-odasi',
        label: 'Oturma Odası',
        dataKey: 'nav_living_room',
        href: '/kategori/oturma-odasi',
        subCategories: [
            {
                title: 'Öne Çıkanlar',
                dataKey: 'nav_featured',
                items: [
                    { label: 'Köşe Koltuklar', dataKey: 'nav_corner_sofas', href: '/kategori/kose-koltuklar' },
                    { label: 'İkili Koltuklar', dataKey: 'nav_two_seat_sofas', href: '/kategori/ikili-koltuklar' },
                    { label: 'Tekli Koltuklar', dataKey: 'nav_armchairs', href: '/kategori/tekli-koltuklar' },
                    { label: 'Berjerler', dataKey: 'nav_bergere', href: '/kategori/berjerler' },
                    { label: 'Orta Sehpalar', dataKey: 'nav_coffee_tables', href: '/kategori/orta-sehpalar' },
                    { label: 'Yan Sehpalar', dataKey: 'nav_side_tables', href: '/kategori/yan-sehpalar' },
                    { label: 'Zigon Sehpalar', dataKey: 'nav_nesting_tables', href: '/kategori/zigon-sehpalar' },
                ],
            },
            {
                title: 'Koleksiyonlar',
                dataKey: 'nav_collections',
                items: [
                    { label: '2026 İlkbahar', dataKey: 'nav_spring_2026', href: '/koleksiyonlar/2026-ilkbahar' },
                    { label: 'Minimalist Seri', dataKey: 'nav_minimalist_series', href: '/koleksiyonlar/minimalist' },
                    { label: 'Klasik Seri', dataKey: 'nav_classic_series', href: '/koleksiyonlar/klasik' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Luna Köşe Koltuk',
            nameKey: 'nav_luna_sofa',
            brand: 'MAISON Atelier',
            brandKey: 'nav_brand_atelier',
            price: 74990,
            originalPrice: 89990,
            image: '/images/products/luna-kose-koltuk.jpg',
            href: '/urun/luna-kose-koltuk',
            badge: 'YENİ',
            badgeKey: 'nav_badge_new',
        },
        editorialText: 'Bu Sezon Trend: Organik Formlar',
        editorialTextKey: 'nav_ed_living',
        colors: [
            { name: 'Vizon', hex: '#C4A882' },
            { name: 'Antrasit', hex: '#3C3C3C' },
            { name: 'Krem', hex: '#F5F0EB' },
        ],
        promotionText: '🔥 Bu Hafta: Luna Köşe Koltuk\'ta %17 İndirim',
        promotionTextKey: 'nav_promo_living',
    },
    {
        id: 'yatak-odasi',
        label: 'Yatak Odası',
        dataKey: 'nav_bedroom',
        href: '/kategori/yatak-odasi',
        subCategories: [
            {
                title: 'Yataklar',
                dataKey: 'nav_beds',
                items: [
                    { label: 'Çift Kişilik Yataklar', dataKey: 'nav_double_beds', href: '/kategori/cift-kisilik-yataklar' },
                    { label: 'Tek Kişilik Yataklar', dataKey: 'nav_single_beds', href: '/kategori/tek-kisilik-yataklar' },
                    { label: 'Baza & Başlıklar', dataKey: 'nav_bases_headboards', href: '/kategori/baza-basliklar' },
                ],
            },
            {
                title: 'Depolama',
                dataKey: 'nav_storage',
                items: [
                    { label: 'Gardıroplar', dataKey: 'nav_wardrobes', href: '/kategori/gardiroplar' },
                    { label: 'Komodinler', dataKey: 'nav_nightstands', href: '/kategori/komodinler' },
                    { label: 'Şifoniyerler', dataKey: 'nav_dressers', href: '/kategori/sifoniyerler' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Aria Platform Yatak',
            nameKey: 'nav_aria_bed',
            brand: 'MAISON Sleep',
            brandKey: 'nav_brand_sleep',
            price: 54990,
            image: '/images/products/aria-platform-yatak.jpg',
            href: '/urun/aria-platform-yatak',
        },
        editorialText: 'Dinlendirici Uyku İçin Tasarlandı',
        editorialTextKey: 'nav_ed_bedroom',
        promotionText: '🔥 Bu Hafta: Yatak Setlerinde %20 İndirim',
        promotionTextKey: 'nav_promo_bedroom',
    },
    {
        id: 'yemek-odasi',
        label: 'Yemek Odası',
        dataKey: 'nav_dining',
        href: '/kategori/yemek-odasi',
        subCategories: [
            {
                title: 'Masa & Sandalye',
                dataKey: 'nav_table_chair',
                items: [
                    { label: 'Yemek Masaları', dataKey: 'nav_dining_tables', href: '/kategori/yemek-masalari' },
                    { label: 'Sandalyeler', dataKey: 'nav_chairs', href: '/kategori/sandalyeler' },
                    { label: 'Bar Tabureleri', dataKey: 'nav_bar_stools', href: '/kategori/bar-tabureleri' },
                ],
            },
            {
                title: 'Depolama',
                dataKey: 'nav_storage',
                items: [
                    { label: 'Büfeler', dataKey: 'nav_sideboards', href: '/kategori/bufeler' },
                    { label: 'Vitrinler', dataKey: 'nav_showcases', href: '/kategori/vitrinler' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Oslo Yemek Masası',
            nameKey: 'nav_oslo_table',
            brand: 'MAISON Studio',
            brandKey: 'nav_brand_studio',
            price: 38990,
            image: '/images/products/oslo-yemek-masasi.jpg',
            href: '/urun/oslo-yemek-masasi',
        },
        promotionText: '🔥 Sandalye Setlerinde %15 İndirim',
        promotionTextKey: 'nav_promo_dining',
    },
    {
        id: 'calisma-odasi',
        label: 'Çalışma Odası',
        dataKey: 'nav_office',
        href: '/kategori/calisma-odasi',
        subCategories: [
            {
                title: 'Çalışma Mobilyası',
                dataKey: 'nav_office_furn',
                items: [
                    { label: 'Çalışma Masaları', dataKey: 'nav_desks', href: '/kategori/calisma-masalari' },
                    { label: 'Ofis Koltukları', dataKey: 'nav_office_chairs', href: '/kategori/ofis-koltuklari' },
                    { label: 'Kitaplıklar', dataKey: 'nav_bookcases', href: '/kategori/kitapliklar-calisma' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Studio Çalışma Masası',
            nameKey: 'nav_studio_desk',
            brand: 'MAISON Work',
            brandKey: 'nav_brand_work',
            price: 29990,
            image: '/images/products/studio-calisma-masasi.jpg',
            href: '/urun/studio-calisma-masasi',
        },
        promotionText: '🔥 Ev Ofis Setlerinde Ücretsiz Kargo',
        promotionTextKey: 'nav_promo_office',
    },
    {
        id: 'aydinlatma',
        label: 'Aydınlatma',
        dataKey: 'nav_lighting',
        href: '/kategori/aydinlatma',
        subCategories: [
            {
                title: 'Aydınlatma Türleri',
                dataKey: 'nav_lighting_types',
                items: [
                    { label: 'Avizeler', dataKey: 'nav_chandeliers', href: '/kategori/avizeler' },
                    { label: 'Lambaderler', dataKey: 'nav_floor_lamps', href: '/kategori/lambaderler' },
                    { label: 'Masa Lambaları', dataKey: 'nav_table_lamps', href: '/kategori/masa-lambalari' },
                    { label: 'Aplik & Spotlar', dataKey: 'nav_sconces_spots', href: '/kategori/aplik-spotlar' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Celeste Avize',
            nameKey: 'nav_celeste_chan',
            brand: 'MAISON Light',
            brandKey: 'nav_brand_light',
            price: 18990,
            image: '/images/products/celeste-avize.jpg',
            href: '/urun/celeste-avize',
            badge: 'TREND',
            badgeKey: 'cat_badge_trend',
        },
        promotionText: '🔥 Aydınlatmada Ücretsiz Montaj',
        promotionTextKey: 'nav_promo_lighting',
    },
    {
        id: 'dekorasyon',
        label: 'Dekorasyon',
        dataKey: 'nav_decoration',
        href: '/kategori/dekorasyon',
        subCategories: [
            {
                title: 'Dekoratif Ürünler',
                dataKey: 'nav_decorative_items',
                items: [
                    { label: 'Vazolar', dataKey: 'nav_vases', href: '/kategori/vazolar' },
                    { label: 'Aynalar', dataKey: 'nav_mirrors', href: '/kategori/aynalar' },
                    { label: 'Halılar', dataKey: 'nav_rugs', href: '/kategori/halilar' },
                    { label: 'Yastık & Kırlentler', dataKey: 'nav_pillows', href: '/kategori/yastik-kirlentler' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Marble Vase Set',
            nameKey: 'nav_marble_vase',
            brand: 'MAISON Decor',
            brandKey: 'nav_brand_decor',
            price: 4990,
            image: '/images/products/marble-vase-set.jpg',
            href: '/urun/marble-vase-set',
        },
        promotionText: '🔥 Dekorasyonda 3 Al 2 Öde',
        promotionTextKey: 'nav_promo_decor',
    },
    {
        id: 'ilham-rehberler',
        label: 'İlham ve Rehberler',
        dataKey: 'nav_inspiration',
        href: '/blog',
        subCategories: [
            {
                title: 'Dekorasyon Rehberleri',
                dataKey: 'nav_decor_guides',
                items: [
                    { label: 'Küçük Salon Çözümleri', dataKey: 'nav_guide_small_living', href: '/blog/kucuk-salona-mobilya-secimi-rehberi' },
                    { label: 'Renk Trendleri 2026', dataKey: 'nav_guide_color_trends', href: '/blog/2026-ev-dekorasyonu-renk-trendleri' },
                    { label: 'Yemek Masası Seçimi', dataKey: 'nav_guide_dining_table', href: '/blog/yemek-masasi-boyutu-nasil-secilir' },
                    { label: 'Minimalist Yatak Odası', dataKey: 'nav_guide_min_bed', href: '/blog/minimalist-yatak-odasi-dekorasyonu' },
                ],
            },
            {
                title: 'Alım Rehberleri',
                dataKey: 'nav_buying_guides',
                items: [
                    { label: 'Ahşap mı, Metal mi?', dataKey: 'nav_guide_wood_metal', href: '/blog/ahsap-mi-metal-mi-malzeme-karsilastirmasi' },
                    { label: 'Çocuk Odası Rehberi', dataKey: 'nav_guide_kids_room', href: '/blog/cocuk-odasi-mobilya-alirken-dikkat-edilecekler' },
                    { label: 'Tüm Yazılar', dataKey: 'nav_guide_all', href: '/blog' },
                ],
            },
            {
                title: 'Keşfet',
                dataKey: 'nav_explore',
                items: [
                    { label: 'Lookbook', dataKey: 'nav_lookbook', href: '/lookbook' },
                    { label: 'Oda Planlayıcı', dataKey: 'nav_room_planner', href: '/oda-planlayici' },
                    { label: 'Kampanyalar', dataKey: 'nav_campaigns', href: '/kampanyalar' },
                ],
            },
        ],
        featuredProduct: {
            name: 'Küçük Salon için 5 Koltuk',
            nameKey: 'nav_blog_small_living',
            brand: 'Dekorasyon Rehberi',
            brandKey: 'nav_brand_decor_guide',
            price: 0,
            image: '/images/gallery-1.jpg',
            href: '/blog/kucuk-salona-mobilya-secimi-rehberi',
            badge: 'YENİ',
            badgeKey: 'nav_badge_new',
        },
        editorialText: 'Uzman tavsiyeleri, ilham veren mekanlar.',
        editorialTextKey: 'nav_ed_inspire',
        promotionText: '✨ Haftanın yazısı: 2026 Renk Trendleri',
        promotionTextKey: 'nav_promo_inspire',
    },
];
