import type { CategoryItem } from './category.types';

export const CATEGORIES: CategoryItem[] = [
    {
        id: 'oturma-odasi',
        label: 'Oturma Odası',
        labelKey: 'nav_living_room',
        subLabel: 'Koleksiyon',
        subLabelKey: 'cat_col',
        productCount: 48,
        href: '/kategori/oturma-odasi',
        image: '/images/categories/living-room.jpg',
        badge: 'Yeni Sezon',
        badgeKey: 'cat_badge_new',
        featured: true,
        span: 5,
    },
    {
        id: 'yatak-odasi',
        label: 'Yatak Odası',
        labelKey: 'nav_bedroom',
        subLabel: 'Kategori',
        subLabelKey: 'cat_cat',
        productCount: 36,
        href: '/kategori/yatak-odasi',
        image: '/images/categories/bedroom.jpg',
        span: 7,
    },
    {
        id: 'yemek-odasi',
        label: 'Yemek Odası',
        labelKey: 'nav_dining',
        subLabel: 'Kategori',
        subLabelKey: 'cat_cat',
        productCount: 24,
        href: '/kategori/yemek-odasi',
        image: '/images/categories/dining.jpg',
        span: 5,
    },
    {
        id: 'calisma-odasi',
        label: 'Çalışma Odası',
        labelKey: 'nav_office',
        subLabel: 'Kategori',
        subLabelKey: 'cat_cat',
        productCount: 18,
        href: '/kategori/calisma-odasi',
        image: '/images/categories/office.jpg',
        span: 7,
    },
    {
        id: 'aydinlatma',
        label: 'Aydınlatma',
        labelKey: 'nav_lighting',
        subLabel: 'Koleksiyon',
        subLabelKey: 'cat_col',
        productCount: 32,
        href: '/kategori/aydinlatma',
        image: '/images/categories/lighting.jpg',
        span: 5,
    },
    {
        id: 'dekorasyon',
        label: 'Dekorasyon',
        labelKey: 'nav_decoration',
        subLabel: 'Koleksiyon',
        subLabelKey: 'cat_col',
        productCount: 56,
        href: '/kategori/dekorasyon',
        image: '/images/categories/decor.jpg',
        badge: 'Trend',
        badgeKey: 'cat_badge_trend',
        span: 7,
    },
];

// Maps category id to filter tab key
export const CATEGORY_FILTER_MAP: Record<string, string> = {
    'oturma-odasi': 'Oturma',
    'yatak-odasi': 'Yatak',
    'yemek-odasi': 'Yemek',
    'calisma-odasi': 'Çalışma',
    'aydinlatma': 'Aydınlatma',
    'dekorasyon': 'Tümü',
};
